### ISSUE TITLE
[Refactoring] Remove sequelize model parameters of query methods

### ISSUE THREAD

**Issue by Sandwichj** [dooboolab/hackatalk-server#16]
This issue follows after merging https://github.com/dooboolab/hackatalk-server/pull/13.

Sequelize model parameter should not pass as an argument for convenience.
The model objects for the methods to query, should be used directly in each model file.

For example,

Bad
```js
// src/model/Chat.ts

export const getChatsByChatroomId = (Chat, chatroomId) => {
  ...
};
```

Good
```js
// src/model/Chat.ts

class Chat extends Model {
  ...
}
Chat.init({
  ...
}
export const getChatsByChatroomId = (chatroomId) => {  // No model parameter
  ...
};
```

**Comment by hyochan** [comment]
Close this since we won't do any further function implementation in `Models`.
