### ISSUE TITLE
[Feature] Update profile

### ISSUE THREAD

**Issue by Sandwichj** [dooboolab/hackatalk-server#52]
derived from https://github.com/dooboolab/hackatalk-mobile/issues/98

## Status
|Component  |Implement                  |Test                             |
|-------------|---------------------|---------------------|
|Resizing an image            |Done                            |Rejected by an issue                    |
|API call - Uploading an image to the server               |Done                             |No test    |
|API call - Update profile           |Not yet                          |Not yet                          |
|API - Uploading an image to the server (Refactoring)            |Take me!                            |Take me!     |
|API - Update profile (Refactoring)          |Take me!                           |Take me!                     |

## Goal

- Implementing Profile upload related APIs with test codes.
- Implementing File upload API with test codes. #33 
- Implementing Profile upload related API calls in [hackatalk-mobile](https://github.com/dooboolab/hackatalk-mobile).

## Releated sources 
- [hacktalk-mobile - ProfileUpdate.tsx](https://github.com/dooboolab/hackatalk-mobile/blob/master/src/components/screen/ProfileUpdate.tsx)

## Requirements
- [Hackatalk mobile](https://github.com/dooboolab/hackatalk-mobile) (react-native)
  - Resizing an image (in Hackatalk app)
    - [expo - image manipulator](https://docs.expo.io/versions/latest/sdk/imagemanipulator/?redirected)
  - API call - Uploading an image to the server
    - by REST API - /upload_single
  - API call - Update profile
    - by GraphQL query

- [Hackatalk server](https://github.com/dooboolab/hackatalk-server) (express server)
  - API - Uploading an image to the server (Already implemented. Refactoring, if needed)
    - by REST API - /upload_single
  - API - Update profile (Already implemented. Refactoring, if needed)
    - by GraphQL [Apollo server](https://www.apollographql.com/)
    - GraphQL schemes
    - GraphQL resolvers
    - Sequelize models

**Comment by chajeehyung** [comment]
안녕하세요
