### ISSUE TITLE
Need to add `thumbURL` and `photoURL`

### ISSUE THREAD

**Issue by geoseong** [dooboolab/hackatalk-server#57]
Seeing the [mobile code](https://github.com/dooboolab/hackatalk-mobile/blob/master/src/components/screen/SearchUser.tsx), I found there's something missing props  from server.
Seeing the capture below, there's photos in each user's information area.
![searchuser](https://user-images.githubusercontent.com/19166187/75092416-a80e2a00-55ba-11ea-8da2-b366e585dfd1.png)

so `thumbURL` and `photoURL` in input type called `UserQueryInput` needed.

When users update profile, their profile photos should be updated to `photoURL` and resized photo to `thumbURL`.

here's `UserQueryInput` input props now.

<img width="506" alt="userprofileinput" src="https://user-images.githubusercontent.com/19166187/75092417-a93f5700-55ba-11ea-838f-75d94e6bd217.png" />

should I PR about to resolve that? or something else needed to check?

please let me know.

**Comment by hyochan** [comment]
You can always give a `PR` if you think something should be changed necessarily without asking beforehand. Why not just `PR`ing first if it isn't the heavy fixes?

**Comment by hyochan** [comment]
Also, it looks like it should be changed 👍
