### ISSUE TITLE
Some Query and Mutation(e.g. createChannel, galleries) is not working

### ISSUE THREAD

**Issue by daadaadaah** [dooboolab/hackatalk-server#72]
### Development environment faced the error
OS : macOS Catalina 10.15.3
MySQL : 8.0.19
Node : v12.16.1
NPM : 6.13.4
yarn : v1.22.4
Sequelize CLI : 5.5.1
ORM: 5.21.5

### Expected behavior
![image](https://user-images.githubusercontent.com/60481383/77220524-568a9800-6b84-11ea-8f7a-536449a00d73.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/60481383/77220782-c9950e00-6b86-11ea-900e-0fd21282abdf.png)

### Steps to reproduce the behavior
1. Clone hackatalk-server repo
2. yarn install
3. Create test_db Database
4. Create MySQL user (ID : hackatalk, PW: hackatalk!)
5. Give user(ID: hackatalk) permission
6. yarn migrate:dev
7. yarn start
8. Access http://localhost:4000/graphql  
9. Execute Signup Mutation three times 
10. Execute createChannel Mutation
11. The following error occurred. This error occurred when I executed galleries Query, createGallery Mutation. 
![image](https://user-images.githubusercontent.com/60481383/77221214-04994080-6b8b-11ea-96e8-b24110222b59.png)

12. The same error occurred when I accessed https://stage.hackatalk.dev/graphql
![image](https://user-images.githubusercontent.com/60481383/77221132-4aa1d480-6b8a-11ea-8de7-7453a5887470.png)

cf. The follow image is when I executed createGallery Mutation and galleries Query
1) createGallery Query
![image](https://user-images.githubusercontent.com/60481383/77221181-b5531000-6b8a-11ea-8eaf-e21065f84db8.png)

2) galleries Query
![image](https://user-images.githubusercontent.com/60481383/77221255-a28d0b00-6b8b-11ea-85d1-9644a7f2f37e.png)

**Comment by hyochan** [comment]
Resolved issue in March 22th in zoom :)
